apiVersion: v1
kind: Service
metadata:
  name: objectdetection-svc
spec:
  ports:
  - port: 443
    targetPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: objectdetection-metrics-svc
spec:
  ports:
  - port: 8081
    targetPort: 8081

