apiVersion: v1
kind: ConfigMap
metadata:
  name: mythicalscissors-config
data:
  RTSP_URL: rtsp://admin:GrandCam1913!@10.0.0.38:554
  CLOUD_BLOB_CONN_STRING: "DefaultEndpointsProtocol=https;AccountName=mythicalisafactorystore;AccountKey=BSwBAM91L3LzDG8R1/aeZ5HRy75GcRO0lCBFNUl6Vl1PWUZL9Ld45b7Is1ECqawLrS7MknnLj1F8+AStcatWqQ==;EndpointSuffix=core.windows.net"
  EDGE_BLOB_CONN_STRING: "DefaultEndpointsProtocol=http;BlobEndpoint=http://azureblobstorageoniotedge:11002/factorystore;AccountName=factorystore;AccountKey=vcjwid76cp2Tk1XMvHfD94tW9wGC6ooBpkj+2I0di5gMV5VjAqxMeSxrNcpc1+1W5aQORY2bMSumGYNnpXoRJA==;"
  EDGE_INFERENCE_URL: "http://mythicalscissorsobjdetectionsvc:8080/image"
  EDGE_BLOB_CONTAINER_NAME: "scissors"
  LOGGING_LEVEL: INFO
  SCOPE_KEYS: plant,edge,line,workload
  SCOPE_VALUES: "FLOWERMOUND,MYTHICALAKSEE,FM407,MYTHICALSCISSORS"
  PROMETHEUS_PORT: "8081"
  SLEEP_TIME: "1"
  APP_NAME: mythicalscissors
  APP_VERSION:

---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-blob-conn-string
type: Opaque
stringData:
  CLOUD_BLOB_CONN_STRING: "CLOUD_BLOB_CONN_STRING"
---