# Labels and Selectors applied by Kustomize
# ImageTag applied by Kustomize
# Environment Variables loaded using ConfigMap and Secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: objdetection
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: objectdetection
        image: objdetection     
        imagePullPolicy: Always
        imagePullSecrets:
        - name: regcred        
        ports:
          - containerPort: 9376
            name: api
          - containerPort: 8081
            name: metrics
        env:
          - name: RTSP_URL
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: RTSP_URL # The key to fetch.
          - name: CLOUD_BLOB_CONN_STRING
            valueFrom:
              secretKeyRef:
                name: cloud-blob-conn-string
                key: CLOUD_BLOB_CONN_STRING            
          - name: EDGE_INFERENCE_URL
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: EDGE_INFERENCE_URL # The key to fetch.
          - name: EDGE_BLOB_CONTAINER_NAME
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: EDGE_BLOB_CONTAINER_NAME # The key to fetch.
          - name: LOGGING_LEVEL
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: LOGGING_LEVEL # The key to fetch.
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: APP_NAME # The key to fetch.
          - name: SCOPE_KEYS
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: SCOPE_KEYS # The key to fetch.
          - name: SCOPE_VALUES
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: SCOPE_VALUES # The key to fetch.
          - name: PROMETHEUS_PORT
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: PROMETHEUS_PORT # The key to fetch.
          - name: SLEEP_TIME
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: SLEEP_TIME # The key to fetch.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actionrules
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: actionrules
        image: actionrules     
        imagePullPolicy: Always
        imagePullSecrets:
        - name: regcred        
        ports:
          - containerPort: 9376
            name: api
          - containerPort: 8081
            name: metrics
        env:
          - name: LOGGING_LEVEL
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: LOGGING_LEVEL # The key to fetch.
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: APP_NAME # The key to fetch.
          - name: SCOPE_KEYS
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: SCOPE_KEYS # The key to fetch.
          - name: SCOPE_VALUES
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: SCOPE_VALUES # The key to fetch.
          - name: PROMETHEUS_PORT
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: PROMETHEUS_PORT # The key to fetch.
          - name: SLEEP_TIME
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: SLEEP_TIME # The key to fetch.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtspimagecapture
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: rtspimagecapture
        image: rtspimagecapture     
        imagePullPolicy: Always
        imagePullSecrets:
        - name: regcred        
        ports:
          - containerPort: 9376
            name: api
          - containerPort: 8081
            name: metrics
        env:
          - name: LOGGING_LEVEL
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: LOGGING_LEVEL # The key to fetch.
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: APP_NAME # The key to fetch.
          - name: SCOPE_KEYS
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: SCOPE_KEYS # The key to fetch.
          - name: SCOPE_VALUES
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: SCOPE_VALUES # The key to fetch.
          - name: PROMETHEUS_PORT
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: PROMETHEUS_PORT # The key to fetch.
          - name: SLEEP_TIME
            valueFrom:
              configMapKeyRef:
                name: mythicalscissors-config  # The ConfigMap this value comes from.
                key: SLEEP_TIME # The key to fetch.
