apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

commonLabels:
  app: mythicalscissors
  environment: dev
  line: jp1913 



images:
- name: objdetection
  newName: mythicalcon.azurecr.io/scissors/objdetection
  newTag: IMAGE_TAG

