trigger:
  branches:
    include:
      - main  
  paths:
    include:
      - solutions/scissors/.pipelines/action-rules-ci.yml
      - solutions/scissors/.pipelines/obj-detection-ci.yml
      - solutions/scissors/.pipelines/rtsp-imgcapture-ci.yml

variables:
  imageACRRepository: "scissors"
  imageTag: '$(Build.BuildId)'
  workingDir: '$(Build.SourcesDirectory)/solutions/scissors'
  unittest_reportprefix: 'mythicalx'
  pythonversion: '3.9'
  srcRepoName: "MythicalKAN"
  opsRepoName: "MythicalArcOps"
  keyVaultName: "mythicalarcopskv"
  subscriptionName: "Mythical-JAYPADDY-LAB"
  acrServiceConnectionName: "mythicalconACRServiceConnection"

stages:
  - stage: actionrules
    displayName: 'Build MythicalScissors Action Rules'
    jobs:
      - template: ./action-rules-ci.yml
        parameters:
          imageRepository: '$[variables.imageACRRepository]/actionrules'
          imageTag: $[variables.imageTag]
          workingDir: '$[variables.workingDir]/MythicalScissorsActionRules'
          unittest_reportprefix: '$[variables.unittest_reportprefix]-mythicalxactionrules'
          pythonversion: $[variables.pythonversion]
          srcRepoName: $[variables.srcRepoName]
          opsRepoName: $[variables.opsRepoName] 
          keyVaultName: $[variables.keyVaultName] 
          subscriptionName: $[variables.subscriptionName]
          acrServiceConnectionName: $[variables.acrServiceConnectionName]


