# build, test (to be built) and push to container registry

trigger:
- main

variables:
- template: variables.yml

pool:
  vmImage: ubuntu-latest

stages:

- stage: bake_kustomize_pr_manifest
  jobs:
  - job: execute_bake_kustomize_pr_manifest
    steps:
    - template: ./templates/bake-manifest-ci.yml
      parameters:
          imageTag: 101
          workingDir: ${{ variables.workingDir }}
  - job: execute_make_pr_to_gitopsrepo
    dependsOn: execute_bake_kustomize_pr_manifest
    steps:
    - template: ./templates/cd-mythicalscissors-pr.yml
      parameters:
          imageTag: ${{ variables.imageTag }}
          workingDir: ${{ variables.workingDir }}
          azure_connection_name: ${{ variables.azure_connection_name }}
          keyvault_name: ${{ variables.keyvault_name }}  
          acr_connect_name: $${{ variables.acr_connect_name}}        
          src_repo_name: ${{ variables.src_repo_name }}      
          ops_repo_name: ${{ variables.ops_repo_name }} 
          manifests_bundle: $[ dependencies.execute_bake_kustomize_pr_manifest.outputs['azureVariables.MANIFESTS_BUNDLE'] ]
