# build, test (to be built) and push to container registry

trigger:
- main

variables:
- template: variables.yml

pool:
  vmImage: ubuntu-latest

stages:
- stage: build_push_action_rules
  jobs:
  - job: execute_build_push_action_rules
    steps:
    - template: action-rules-ci.yml
      parameters:
          imageRepository: ${{ variables.imageRepository }}
          imageTag: ${{ variables.imageTag }}
          workingDir: ${{ variables.workingDir }}
          unittest_reportprefix: ${{ variables.unittest_reportprefix }}
          pythonversion: ${{ variables.pythonversion }}
          azure_connection_name: ${{ variables.azure_connection_name }}
          keyvault_name: ${{ variables.keyvault_name }}

