# build, test (to be built) and push to container registry

trigger:
- main

variables:
- template: variables.yml

pool:
  vmImage: ubuntu-latest

stages:
- stage: build_push_action_rules
  jobs:
  - job: execute_build_push_action_rules
    steps:
    - template: action-rules-ci.yml
      parameters:
          imageRepository: ${{ variables.imageRepository }}
          imageTag: ${{ variables.imageTag }}
          workingDir: ${{ variables.workingDir }}
          unittest_reportprefix: ${{ variables.unittest_reportprefix }}
          pythonversion: ${{ variables.pythonversion }}
          azure_connection_name: ${{ variables.azure_connection_name }}
          keyvault_name: ${{ variables.keyvault_name }}
          acr_connect_name: ${{ variables.acr_connect_name}}  
          project_name: ${{ variables.actionrules_project_name }}      
          image_name: ${{ variables.actionrules_image_name }}      

- stage: build_push_object_detection
  jobs:
  - job: execute_build_push_object_detection
    steps:
    - template: obj-detection-ci.yml
      parameters:
          imageRepository: ${{ variables.imageRepository }}
          imageTag: ${{ variables.imageTag }}
          workingDir: ${{ variables.workingDir }}
          unittest_reportprefix: ${{ variables.unittest_reportprefix }}
          pythonversion: ${{ variables.pythonversion }}
          azure_connection_name: ${{ variables.azure_connection_name }}
          keyvault_name: ${{ variables.keyvault_name }}  
          acr_connect_name: $${{ variables.acr_connect_name}}        
          project_name: ${{ variables.objdet_project_name }}      
          image_name: ${{ variables.objdet_image_name }}      

- stage: build_push_rtsp_imgcapture
  jobs:
  - job: execute_build_push_rtsp_imgcapture
    steps:
    - template: rtsp-imgcapture-ci.yml
      parameters:
          imageRepository: ${{ variables.imageRepository }}
          imageTag: ${{ variables.imageTag }}
          workingDir: ${{ variables.workingDir }}
          unittest_reportprefix: ${{ variables.unittest_reportprefix }}
          pythonversion: ${{ variables.pythonversion }}
          azure_connection_name: ${{ variables.azure_connection_name }}
          keyvault_name: ${{ variables.keyvault_name }}  
          acr_connect_name: $${{ variables.acr_connect_name}}        
          project_name: ${{ variables.imgcapture_project_name }}      
          image_name: ${{ variables.imgcapture_image_name }}  