# We are going to Release this app to Staging

# 1. One Final Build tagged as {{ parameters.stageBuildTag}}
# 2. Build all artifacts as {{ parameters.stageBuildTag}} and Push to ACR
# 3. Bake Manifest just to validate the Manifest is correct
# 4. Release to Staging
#   a. Checkout GitOps Repo
#   b. Create a branch named {{ parameters.stageBuildTag}}/{{ parameters.app_name}}/{{ parameters.appVersion }}-{{ parameters.imageTag }}
#   c. Create a folder with {{ parameters.appName}} 
#   d. Copy kustomize folder from source repo to the folder created in step c
#   e. Commit the changes to the branch created in step b
#   f. Create a PR to the branch created in step b 

trigger:
- none

variables:
- template: variables.yml

pool:
  vmImage: ubuntu-latest

stages:

- stage: bake_commit_pr_manifest
  jobs:
  - job: execute_bake_commit_pr_to_gitopsrepo
    steps:
    - template: ./templates/build-copy-commit-pr.yml
      parameters:
          stageBuildTag: ${{ variables.stageBuildTag }}
          workingDir: ${{ variables.workingDir }}
          azure_connection_name: ${{ variables.azure_connection_name }}
          keyvault_name: ${{ variables.keyvault_name }}  
          acr_connect_name: $${{ variables.acr_connect_name}}        
          src_repo_name: ${{ variables.src_repo_name }}  
          dest_branch:  "${{ variable.stageBuildTag}}/${{ variables.app_name}}/${{ variables.appVersion }}/${{ variables.imageTag }}"
          target_environment: ${{ variables.target_environment }}
          config_storage_account_name: ${{ variables.config_storage_account_name }}
