apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
secretGenerator:
- files:
  - secret-docker-reg.json
  name: regcred
  type: kubernetes.io/dockerconfigjson
  namespace: mythicalapp1-ns
images:
- name: mythicalcon.azurecr.io/arc/mythicalapp1:latest
  newName: mythicalcon.azurecr.io/arc/mythicalapp1
  newTag: IMAGE_TAG
