apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base

resources:
- ./namespace.yaml
- ./configMap.yaml

namespace: mythicalscissors-ns
commonLabels:
  app: mythicalscissors
  environment: dev
  line: jp1913 
  plant: mythicalaksee

secretGenerator:
- files:
  - secret-docker-reg.json
  name: regcred
  type: kubernetes.io/dockerconfigjson

images:
- name: objdetection
  newName: mythicalcon.azurecr.io/scissors/objdetection
  newTag: IMAGE_TAG
- name: actionrules
  newName: mythicalcon.azurecr.io/scissors/actionrules
  newTag: IMAGE_TAG
- name: rtspimagecapture
  newName: mythicalcon.azurecr.io/scissors/rtspimgcapture
  newTag: IMAGE_TAG  
