apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Name }}
  labels:
    name: mythicalarck3s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mythicalapp1
  labels:
    app: mythicalapp1
  namespace: {{ .Release.Name }}-ns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mythicalapp1
  template:
    metadata:
      labels:
        app: mythicalapp1
    spec:
      containers:
      - name: mythicalapp1
        image: {{ .Values.global.image.registry }}/mythicalapp1:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        imagePullSecrets:
        - name: regcred        
        resources:
          requests:
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "500m"        
                                           
             
