apiVersion: v1
kind: Namespace
metadata:
  name: mythicalscissors-ns
  labels:
    name: mythicalscissors
---
apiVersion: v1
data:
  RTSP_URL: rtsp://admin:GrandCam1913!@10.0.0.38:554
  CLOUD_BLOB_CONN_STRING: "DefaultEndpointsProtocol=https;AccountName=mythicalisafactorystore;AccountKey=BSwBAM91L3LzDG8R1/aeZ5HRy75GcRO0lCBFNUl6Vl1PWUZL9Ld45b7Is1ECqawLrS7MknnLj1F8+AStcatWqQ==;EndpointSuffix=core.windows.net"
  EDGE_BLOB_CONN_STRING: "DefaultEndpointsProtocol=http;BlobEndpoint=http://azureblobstorageoniotedge:11002/factorystore;AccountName=factorystore;AccountKey=vcjwid76cp2Tk1XMvHfD94tW9wGC6ooBpkj+2I0di5gMV5VjAqxMeSxrNcpc1+1W5aQORY2bMSumGYNnpXoRJA==;"
  EDGE_INFERENCE_URL: "http://mythicalscissorsobjdetectionsvc:8080/image"
  EDGE_BLOB_CONTAINER_NAME: "scissors"
  LOGGING_LEVEL: INFO
  APP_NAME: mythicalapp
  SCOPE_KEYS: plant,edge,line,workload
  SCOPE_VALUES: "FLOWERMOUND,MYTHICALAKSEE,FM407,MYTHICALSCISSORS"
  PROMETHEUS_PORT: 8081
  SLEEP_TIME: 1

kind: ConfigMap
metadata:
  labels:
    line: mk80
    usecase: demo
  name: demo-collector-config-mk80
  namespace: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mythicalscissors
  labels:
    app: mythicalscissors
  namespace: mythicalscissors-ns

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mythicalscissors
  template:
    metadata:
      labels:
        app: mythicalscissors
    spec:
      containers:
      - name: objectdetection
        image: templateRegistry/mythicalobjdetection:latest     
        imagePullPolicy: Always
        imagePullSecrets:
        - name: regcred        
        resources:
          requests:
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "500m"  
      - name: actionrules
        image: templateRegistry/mythicalactionrules:latest     
        imagePullPolicy: Always
        imagePullSecrets:
        - name: regcred        
        resources:
          requests:
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "500m"                    
      - name: rtspcapture
        image: templateRegistry/mythicalrtspcapture:latest     
        imagePullPolicy: Always
        imagePullSecrets:
        - name: regcred        
        resources:
          requests:
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "500m"                    
                                           
                                                        
             
